-- Migration pour insérer tous les articles du blog depuis blogData.ts vers la table blog_articles

INSERT INTO public.blog_articles (id, title, description, category, image, status, created_at, updated_at, publish_date) VALUES
  (gen_random_uuid(), 'Origin of Tunisia''s Name', 'The country''s official name is the Republic of Tunisia, or ''Tunis'' in the Tunisian Arabic dialect. The meaning behind this name originates from the word ''Tawannas''...', 'history', '/uploads/fec14bc8-485f-4387-8e22-ecd6ecd486cc.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Tunisia''s Capital City', 'Tunis is the capital and largest city of Tunisia. Located on the Mediterranean coast but tucked into a bay in the Gulf of Tunis...', 'places', '/uploads/2cd4bbc7-9d42-427b-bd7e-753d75c3f452.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Best Hotels in Tunis', 'Discover the finest accommodations in Tunisia''s capital, from luxury beachfront resorts to charming boutique hotels in the medina...', 'hotels', 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&auto=format&fit=crop', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Traditional Tunisian Cuisine', 'Explore the rich flavors of Tunisian cuisine, from spicy harissa to couscous dishes and fresh Mediterranean seafood...', 'food', '/uploads/3eb94eb6-e87e-4fa3-96a1-7458222397fb.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Upcoming Cultural Events', 'Don''t miss these exciting cultural festivals and events happening across Tunisia in the coming months...', 'events', 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Tunisian Wedding Traditions', 'Learn about the fascinating wedding customs and celebrations that are an integral part of Tunisian culture...', 'culture', '/uploads/3ad71d34-2716-4f06-b270-b0bf29374408.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Historical Timeline', 'Tunisia''s rich history spans thousands of years, from ancient Carthage through Roman rule, Arab conquest, Ottoman control...', 'history', '/uploads/f66ee597-e8d7-44b5-834e-d0eb1266a0ba.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Essential Travel Tips', 'Make the most of your Tunisian adventure with these important travel tips covering transportation, accommodation, and local customs...', 'tips', '/uploads/db9ae52d-84f3-4ecf-9d5b-561f4ba51a50.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Best Beaches in Tunisia', 'Discover the most beautiful beaches along Tunisia''s Mediterranean coastline, from popular resort areas to hidden coves...', 'places', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Local Transportation Guide', 'Navigate Tunisia like a pro with our comprehensive guide to local transportation options...', 'tips', 'https://images.unsplash.com/photo-1494515843206-f3117d3f51b7?w=800&auto=format&fit=crop', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Desert Adventures', 'Experience the magic of the Sahara with our guide to desert camps, camel treks, and stargazing adventures...', 'travel-diary', '/uploads/3caaa473-8150-4b29-88b4-e2e9c696bf1d.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Tunisian Architectural Heritage', 'Explore the mesmerizing world of Tunisian architecture, featuring intricate tilework, historic arches, and the blend of cultural influences that shape the country''s unique architectural identity...', 'culture', '/uploads/39525830-588c-4a66-a55b-1cb773fb6305.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'The Tunisian Flag: Symbolism and Origin', 'Discover the rich history and profound symbolism behind Tunisia''s national flag, featuring its distinctive red background with a white circle containing a crescent moon and star...', 'history', '/uploads/166190fd-2e2c-4775-85d4-d60b0316ba74.png', 'published', now(), now(), now()),
  (gen_random_uuid(), 'Modern Tunisian Art Scene', 'Explore Tunisia''s vibrant contemporary art scene, where traditional craftsmanship meets modern expression. From bustling galleries in Tunis to emerging artists shaping the cultural landscape...', 'culture', '/uploads/bd5ba590-fb88-434b-b2b0-a6eae62e1144.png', 'published', now(), now(), now());